name: Eversoul
version: '${project.version}'
main: com.raaaaming.eversoul.eversoul.Main
api-version: 1.18
authors: [ raaaaming ]
description: dd

commands:
  es:
    description: 해당 명령어로 방주 메타트론을 제어할 수 있습니다.
    usage: /es help
    aliases:
      - 에버소울
      - 에소
      - eversoul